name: "Linting"

on:
  push:
  pull_request:


jobs:
  lint:
    name: "Linting"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v3.5.2"

        - name: "Set up Python"
          uses: actions/setup-python@v4.6.1
          with:
            python-version: "3.11"
            cache: "pip"

        - name: "Install requirements"
          run: python3 -m pip install -r requirements.txt

        - name: "Run isort"
          run: python3 -m isort --check --profile black .

        - name: "Run Black"
          run: python3 -m black --check .

        - name: "Run Ruff"
          run: python3 -m ruff check -q .
