name: Validate with hassfest

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
  schedule:
    - cron: "1 1 * * 6"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: home-assistant/actions/hassfest@master
